apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-min
  namespace: events-min
spec:
  ingressClassName: nginx
  rules:
    - host: events-dev.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: events-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: events-frontend-lb
                port:
                  number: 80
