apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: events-min
resources:
  - namespace.yaml
  - api-deploy.yaml
  - api-svc.yaml
  - frontend-deploy.yaml
  - frontend-svc-lb.yaml
  - ingress.yaml

images:
  - name: ghcr.io/example/events-api
    newName: ghcr.io/kickoffqi/events-api
    newTag: sha-1b136e2
  - name: ghcr.io/example/events-frontend
    newName: ghcr.io/kickoffqi/events-frontend
    newTag: sha-1b136e2
