apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: events.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: events-frontend
                port:
                  number: 80
