apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: events
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-dns.yaml
  - networkpolicy-allow-frontend-ingress.yaml
  - networkpolicy-allow-frontend-egress.yaml
  - networkpolicy-allow-api-ingress.yaml
  - istio-peerauthentication.yaml
  - istio-authorizationpolicy.yaml
