apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-frontend
spec:
  rules:
    - host: events-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: events-frontend
                port:
                  number: 80
