apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/example/events-api
    newName: ghcr.io/kickoffqi/events-api
    newTag: sha-3ff0f06
  - name: ghcr.io/example/events-frontend
    newName: ghcr.io/kickoffqi/events-frontend
    newTag: sha-3ff0f06
patches:
  - path: ingress-host-patch.yaml
  - path: imagepullpolicy-patch.yaml
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: events-api
