apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/example/events-api
    newTag: dev
  - name: ghcr.io/example/events-frontend
    newTag: dev
patches:
  - path: ingress-host-patch.yaml
